language: node_js
node_js:
  - '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
    - CXX=g++-4.8
    - REDIS_URL=redis://localhost:6379
install: npm install
script:
  - npm test
before_install:
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'export DISPLAY=:99.0'
services:
  - 'redis-server'
notifications:
  irc:
    channels:
      - "irc.mozilla.org#wadi"
    skip_join: true
